module.exports = {
  mode: 'jit',
  separator: '_',
  content: ['./public/**/*.{html,js}', './pages/**/*.{html,js}'],
  safelist: [
    'flex',
    'flex-col',
    'flex-wrap',
    'fixed',
    'top-0',
    'left-0',
    'h-screen',
    'w-12',
    'w-16',
    'w-24',
    'w-28',
    'w-32',
    'w-40',
    'w-44',
    'w-48',
    'w-52',
    'w-96',
    'w-3/4',
    'w-1/2',
    'w-auto',
    'h-auto',
    'h-48',
    'object-cover',
    'md_h-full',
    'md_w-48',
    'md_w-48',
    'lg_h-auto',
    'md_h-auto',
    'm-0',
    'm-2',
    'm-3',
    'm-4',
    'mt-4',
    'bg-gray-900',
    'bg-gray-800',
    'bg-gray-700',
    'bg-gray-600',
    'bg-gray-500',
    'bg-gray-400',
    'bg-gray-300',
    'bg-gray-200',
    'bg-gray-100',
    'bg-red-900',
    'bg-red-800',
    'bg-red-700',
    'bg-red-600',
    'bg-red-500',
    'bg-red-400',
    'bg-red-300',
    'bg-red-200',
    'bg-red-100',
    'bg-indigo-900',
    'bg-indigo-800',
    'bg-indigo-700',
    'bg-indigo-600',
    'bg-indigo-500',
    'bg-indigo-400',
    'bg-indigo-300',
    'bg-indigo-200',
    'bg-rose-900',
    'hover_bg-indigo-600',
    'hover_bg-cyan-600',
    'hover_bg-blue-600',
    'hover_bg-sky-600',
    'text-white',
    'text-slate-700',
    'shadow-lg',
    'shadow-md',
    'relative',
    'items-center',
    'justify-center',
    'h-12',
    'mt-4',
    'mt-2',
    'mt-1',
    'mb-2',
    'mb-1',
    'mx-auto',
    'shadow-lg',
    'bg-gray-800',
    'text-green-500',
    'hover_bg-green-600',
    'hover_bg-indigo-600',
    'hover_bg-rose-600',
    'hover_bg-rose-900',
    'hover_bg-rose-800',
    'bg-rose-800',
    'ml-2',
    'ml-4',
    'mr-2',
    'rounded-3xl',
    'rounded-xl',
    'rounded-md',
    'hover_rounded-xl',
    'transition-all',
    'duration-300',
    'ease-linear',
    'cursor-pointer',
    'hover_text-white',
    'absolute',
    'p-2',
    'p-4',
    'p-6',
    'min-w-max',
    'left-14',
    'text-xs',
    'text-lg',
    'text-base',
    'text-sm',
    'text-xl',
    'text-center',
    'font-bold',
    'duration-100',
    'scale-0',
    'origin-left',
    'group',
    'group-hover_scale-100',
    'hover_bg-emerald-600',
    'text-emerald-600',
    'text-red-500',
    'pl-4',
    'inset-x-auto',
    'px-2',
    'px-4',
    'px-16',
    'container',
    'h-10',
    'pl-2',
    'p-2',
    'pb-1',
    'pb-2',
    'hover_bg-gray-600',
    'hover_shadow-lg',
    'hover_text-white',
    'text-gray-500',
    'rounded-lg',
    'flex-1',
    'max-w-md',
    'max-w-lg',
    'max-w-sm',
    'max-w-xs',
    'max-h-20',
    'bg-white',
    'overflow-hidden',
    'text-slate-100',
    'text-slate-200',
    'text-slate-300',
    'text-slate-400',
    'text-slate-500',
    'text-slate-600',
    'text-slate-700',
    'text-slate-800',
    'text-slate-900',
    'text-gray-100',
    'text-gray-200',
    'text-gray-300',
    'text-gray-400',
    'md_max-w-2xl',
    'md_flex',
    'md_shrink-0',
    'w-full',
    'h-full',
    'p-8',
    'uppercase',
    'tracking-wide',
    'text-indigo-500',
    'text-indigo-700',
    'text-indigo-800',
    'font-semibold',
    'block',
    'leading-tight',
    'font-medium',
    'text-black',
    'hover_underline',
    'text-emerald-200',
    'text-indigo-200',
    'text-indigo-300',
    'z-40',
    'scroll-ml-20',
    'ml-52',
  ],
  theme: {
    extend: {
      colors: {
        gray: {
          900: '#202225',
          800: '#2f3136',
          700: '#36393f',
          600: '#4f545c',
          400: '#d4d7dc',
          300: '#e3e5e8',
          200: '#ebedef',
          100: '#f2f3f5',
        },
      },
      spacing: {
        88: '22rem',
      },
    },
  },
  plugins: [],
};
